env:
  browser: true
  es2021: true
extends:
  - plugin:@next/next/recommended
  - plugin:react/recommended
  - standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
plugins:
  - react
rules: {}
ignorePatterns:
  - out/**/*.js
  - node_modules/**/*.js
  - .next/**/*.js
