name: "Build Static Site"

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: "Next.js static build"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@master
        with:
          name: static-output
          path: out

  deploy:
    name: "Deploy to AWS S3"
    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1

      - uses: actions/download-artifact@master
        with:
          name: static-output
          path: out

      - name: Copy files to the test website with the AWS CLI
        if: github.ref_name == 'main' && github.event_name == 'push'
        run: |
          aws s3 sync out s3://tracyding-com-website/
